[0m23:50:52.762262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa056847070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa054c90130>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa054c92a10>]}


============================== 23:50:52.778650 | e8ab865a-9b0c-4212-b42c-80bccbe53a2d ==============================
[0m23:50:52.778650 [info ] [MainThread]: Running with dbt=1.7.19
[0m23:50:52.783817 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/asparsh/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:50:52.787087 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/asparsh/data_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:50:52.796753 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.37358496, "process_user_time": 7.895449, "process_kernel_time": 3.106077, "process_mem_max_rss": "97872", "process_in_blocks": "912", "process_out_blocks": "8", "command_success": false}
[0m23:50:52.798723 [debug] [MainThread]: Command `dbt run` failed at 23:50:52.798081 after 0.38 seconds
[0m23:50:52.800493 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa056847070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa054c92a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa054c93a60>]}
[0m23:50:52.802407 [debug] [MainThread]: Flushing usage events
[0m23:52:10.136455 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5a4cb040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5890fb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5890f280>]}


============================== 23:52:10.147078 | ee7e17a0-9526-421d-b964-fd1fcf1dff9a ==============================
[0m23:52:10.147078 [info ] [MainThread]: Running with dbt=1.7.19
[0m23:52:10.149894 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/asparsh/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:52:10.152802 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/asparsh/data_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:52:10.158246 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.28823617, "process_user_time": 6.774637, "process_kernel_time": 0.949248, "process_mem_max_rss": "97820", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:52:10.160558 [debug] [MainThread]: Command `dbt run` failed at 23:52:10.159738 after 0.29 seconds
[0m23:52:10.162178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5a4cb040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5890f3a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9a5890d300>]}
[0m23:52:10.163910 [debug] [MainThread]: Flushing usage events
